using System.Globalization;
using System.Text;

const string ExpectedUnicodeVersion = "17.0.0";

if ( 2 != args.Length ) {
	Console.Error.WriteLine(
		"Usage: dotnet run --project tools/unicode-width-generator/"
			+ "Icod.DCurses.UnicodeWidthGenerator.csproj -- <EastAsianWidth.txt> <output.cs>"
	);
	return 2;
}

try {
	string inputPath = Path.GetFullPath( args[ 0 ] );
	string outputPath = Path.GetFullPath( args[ 1 ] );
	string[] lines = File.ReadAllLines( inputPath );
	ValidateVersion( lines );

	List<UnicodeRange> ambiguous = [];
	List<UnicodeRange> wide = [];

	foreach ( string rawLine in lines ) {
		string line = rawLine.Split( '#', 2 )[ 0 ].Trim();
		if ( 0 == line.Length ) {
			continue;
		}

		string[] fields = line.Split( ';', 2 );
		if ( 2 != fields.Length ) {
			throw new InvalidDataException(
				$"Malformed EastAsianWidth line: {rawLine}"
			);
		}

		UnicodeRange range = ParseRange( fields[ 0 ].Trim() );
		string property = fields[ 1 ].Trim();
		switch ( property ) {
			case "A":
				AddMerged( ambiguous, range );
				break;

			case "W":
			case "F":
				AddMerged( wide, range );
				break;
		}
	}

	Directory.CreateDirectory(
		Path.GetDirectoryName( outputPath )
			?? throw new InvalidOperationException( "The output path has no parent directory." )
	);
	File.WriteAllText(
		outputPath,
		GenerateSource( ambiguous, wide ),
		new UTF8Encoding( encoderShouldEmitUTF8Identifier: false )
	);

	Console.WriteLine(
		$"Generated Unicode {ExpectedUnicodeVersion} East Asian width data: "
			+ $"{ambiguous.Count} ambiguous ranges, {wide.Count} wide/fullwidth ranges."
	);
	return 0;
} catch ( Exception exception ) when (
	exception is IOException
		or UnauthorizedAccessException
		or InvalidDataException
		or InvalidOperationException
		or FormatException
		or ArgumentException
) {
	Console.Error.WriteLine( exception.Message );
	return 1;
}

static void ValidateVersion( IReadOnlyList<string> lines ) {
	ArgumentNullException.ThrowIfNull( lines );
	string expectedHeader = $"# EastAsianWidth-{ExpectedUnicodeVersion}.txt";
	if ( !lines.Any(
		line => string.Equals(
			line.Trim(),
			expectedHeader,
			StringComparison.Ordinal
		)
	) ) {
		throw new InvalidDataException(
			$"Expected Unicode {ExpectedUnicodeVersion} EastAsianWidth data."
		);
	}
}

static UnicodeRange ParseRange( string field ) {
	ArgumentException.ThrowIfNullOrWhiteSpace( field );
	string[] bounds = field.Split( "..", StringSplitOptions.None );
	if ( bounds.Length is < 1 or > 2 ) {
		throw new InvalidDataException( $"Invalid code-point range '{field}'." );
	}

	int first = int.Parse(
		bounds[ 0 ],
		NumberStyles.AllowHexSpecifier,
		CultureInfo.InvariantCulture
	);
	int last = 1 == bounds.Length
		? first
		: int.Parse(
			bounds[ 1 ],
			NumberStyles.AllowHexSpecifier,
			CultureInfo.InvariantCulture
		)
	;
	if ( first < 0 || last < first || 0x10FFFF < last ) {
		throw new InvalidDataException( $"Invalid code-point range '{field}'." );
	}

	return new UnicodeRange( first, last );
}

static void AddMerged(
	List<UnicodeRange> ranges,
	UnicodeRange next
) {
	ArgumentNullException.ThrowIfNull( ranges );
	if ( 0 == ranges.Count ) {
		ranges.Add( next );
		return;
	}

	UnicodeRange previous = ranges[ ^1 ];
	if ( next.First <= previous.Last + 1 ) {
		ranges[ ^1 ] = new UnicodeRange(
			previous.First,
			Math.Max( previous.Last, next.Last )
		);
		return;
	}

	ranges.Add( next );
}

static string GenerateSource(
	IReadOnlyList<UnicodeRange> ambiguous,
	IReadOnlyList<UnicodeRange> wide
) {
	ArgumentNullException.ThrowIfNull( ambiguous );
	ArgumentNullException.ThrowIfNull( wide );

	StringBuilder source = new();
	source.AppendLine( "namespace Icod.DCurses.Internal.Generated;" );
	source.AppendLine();
	source.AppendLine( "// <auto-generated />" );
	source.AppendLine(
		$"// Generated from Unicode {ExpectedUnicodeVersion} EastAsianWidth.txt."
	);
	source.AppendLine();
	source.AppendLine( "internal readonly record struct UnicodeWidthRange( int First, int Last );" );
	source.AppendLine();
	source.AppendLine( "internal static class UnicodeEastAsianWidthData {" );
	source.AppendLine(
		$"\tinternal const string UnicodeVersion = \"{ExpectedUnicodeVersion}\";"
	);
	source.AppendLine();
	AppendArray( source, "AmbiguousRanges", ambiguous );
	source.AppendLine();
	AppendArray( source, "WideOrFullwidthRanges", wide );
	source.AppendLine( "}" );
	return source.ToString();
}

static void AppendArray(
	StringBuilder source,
	string name,
	IReadOnlyList<UnicodeRange> ranges
) {
	ArgumentNullException.ThrowIfNull( source );
	ArgumentException.ThrowIfNullOrWhiteSpace( name );
	ArgumentNullException.ThrowIfNull( ranges );

	source.AppendLine(
		$"\tinternal static readonly UnicodeWidthRange[] {name} = ["
	);
	foreach ( UnicodeRange range in ranges ) {
		source.AppendLine(
			$"\t\tnew( 0x{range.First:X}, 0x{range.Last:X} ),"
		);
	}
	source.AppendLine( "\t];" );
}

internal readonly record struct UnicodeRange(
	int First,
	int Last
);
